name: Bug Report
description: Report a bug in filigree
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below.
  - type: input
    id: version
    attributes:
      label: Filigree version
      description: "Output of `filigree --version`"
      placeholder: "0.1.0"
    validations:
      required: true
  - type: dropdown
    id: interface
    attributes:
      label: Interface
      description: How were you using filigree?
      options:
        - CLI
        - MCP (Claude Code / other agent)
        - Dashboard
        - Python API
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS:
        - Python version:
        - Installation method (pip/uv/pipx):
      render: text
