# IMPORT CONSTRAINT: types/ modules must only import from typing, stdlib, and each other.
# NEVER import from core.py, db_base.py, or any mixin — this prevents circular imports.
"""Typed return-value contracts for filigree core and API layers."""

from __future__ import annotations

from filigree.types.api import (
    BatchCloseResponse,
    BatchUpdateResponse,
    ClaimNextResponse,
    DepDetail,
    EnrichedIssueDetail,
    ErrorResponse,
    IssueDetailEvent,
    IssueListResponse,
    IssueWithChangedFields,
    IssueWithTransitions,
    IssueWithUnblocked,
    PlanResponse,
    SearchResponse,
    SlimIssue,
    StatsWithPrefix,
    TransitionError,
)
from filigree.types.core import (
    FileRecordDict,
    ISOTimestamp,
    IssueDict,
    PaginatedResult,
    ProjectConfig,
    ScanFindingDict,
)
from filigree.types.events import (
    EventRecord,
    EventRecordWithTitle,
    UndoFailure,
    UndoResult,
    UndoSuccess,
)
from filigree.types.files import (
    CleanStaleResult,
    FileAssociation,
    FileDetail,
    FileHotspot,
    FindingsSummary,
    GlobalFindingsStats,
    HotspotFileRef,
    IssueFileAssociation,
    ScanIngestResult,
    ScanRunRecord,
    SeverityBreakdown,
)
from filigree.types.planning import (
    CommentRecord,
    CriticalPathNode,
    DependencyRecord,
    FlowMetrics,
    PlanPhase,
    PlanTree,
    StatsResult,
    TypeMetrics,
)
from filigree.types.workflow import (
    FieldSchemaInfo,
    StateInfo,
    TemplateInfo,
    TemplateListItem,
    TransitionInfo,
)

__all__ = [
    "BatchCloseResponse",
    "BatchUpdateResponse",
    "ClaimNextResponse",
    "CleanStaleResult",
    "CommentRecord",
    "CriticalPathNode",
    "DepDetail",
    "DependencyRecord",
    "EnrichedIssueDetail",
    "ErrorResponse",
    "EventRecord",
    "EventRecordWithTitle",
    "FieldSchemaInfo",
    "FileAssociation",
    "FileDetail",
    "FileHotspot",
    "FileRecordDict",
    "FindingsSummary",
    "FlowMetrics",
    "GlobalFindingsStats",
    "HotspotFileRef",
    "ISOTimestamp",
    "IssueDetailEvent",
    "IssueDict",
    "IssueFileAssociation",
    "IssueListResponse",
    "IssueWithChangedFields",
    "IssueWithTransitions",
    "IssueWithUnblocked",
    "PaginatedResult",
    "PlanPhase",
    "PlanResponse",
    "PlanTree",
    "ProjectConfig",
    "ScanFindingDict",
    "ScanIngestResult",
    "ScanRunRecord",
    "SearchResponse",
    "SeverityBreakdown",
    "SlimIssue",
    "StateInfo",
    "StatsResult",
    "StatsWithPrefix",
    "TemplateInfo",
    "TemplateListItem",
    "TransitionError",
    "TransitionInfo",
    "TypeMetrics",
    "UndoFailure",
    "UndoResult",
    "UndoSuccess",
]
